import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '~/components/Header';
import SessionMounter from '~/components/Mounter';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Aeropress Tracker</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SessionMounter>
				<Header />
				<h1>Home Page</h1>
			</SessionMounter>
		</div>
	);
};

export default Home;
