import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Aeropress Tracker</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="google-site-verification"
					content="Oa1s8SVVifhLy1mLL9s8KdQi1FQ2VlHa7WAdpe_gK8g"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>HomePage</h1>
		</>
	);
};

export default Home;
